/**
 *  Product List
 */

export default [
    {
        "id": 0,
        "artNo": "1000-0047",
        "name": "Fan Scarf Marathon",
        "slug": "1a",
        "pictures": ["scarves/fan-scarf-marathon.jpg", "scarves/fan-scarf-marathon.jpg"],
        "stock": 32,
        "price": 3500,
        // "discount": 1000,
        "salePrice": 2500,
        "description": "Get your marathon scarf from Wildemasche. Custom knitted with your design and text. Create your runners scarf online. Your favourite text, logo or personal message in a scarf",
        "rating": 5,
        "tags": ["Women"],
        "size": ["M", "XL"],
        "category": "Scarves",
        "colors": ["Red"]
    },
    {
        "id": 1,
        "artNo": "1000-0048",
        "name": "Football Scarf Blue White",
        "slug": "2b",
        "pictures": ["scarves/football-scarf-blue-white.jpg", "scarves/football-scarf-blue-white.jpg"],
        "stock": 32,
        "price": 3500,
        "discount": 1000,
        "salePrice": 2500,
        "description": "Football scarf with half/half design. The custom scarf for your team in blue and white. Design online and create your custom team scarf today. Design with logo, text, cliparts etc. Design is knitted in.",
        "rating": 5,
        "tags": ["Scarves"],
        "size": ["M", "XL"],
        "category": "Scarves",
        "colors": ["Red"]
    },
    {
        "id": 2,
        "artNo": "1000-0049",
        "name": "Football Scarf Darts",
        "slug": "3c",
        "pictures": ["scarves/football-scarf-darts.jpg", "scarves/football-scarf-darts.jpg"],
        "stock": 32,
        "price": 3500,
        "discount": 1000,
        "salePrice": 2500,
        "description": "The bundesliga is the major football / soccer league in Germany. Design your football scarf with custom design, made to order with you team name and logo.",
        "rating": 5,
        "tags": ["Scarves"],
        "size": ["M", "XL"],
        "category": "Scarves",
        "colors": ["Red"]
    },
    {
        "id": 3,
        "artNo": "1000-0050",
        "name": "Football Scarf Leather",
        "slug": "4d",
        "pictures": ["scarves/football-scarf-leather.jpg", "scarves/football-scarf-leather.jpg"],
        "stock": 32,
        "price": 3500,
        "discount": 1000,
        "salePrice": 2500,
        "description": "The first football you can wear around your neck. Customize and order online now.",
        "rating": 5,
        "tags": ["Scarves"],
        "size": ["M", "XL"],
        "category": "Scarves",
        "colors": ["Red"]
    },
    {
        "id": 4,
        "artNo": "1000-0051",
        "name": "Football Scarf Europe",
        "slug": "5e",
        "pictures": ["scarves/football-scarf-europe.jpg", "scarves/football-scarf-europe.jpg"],
        "stock": 32,
        "price": 3500,
        "discount": 1000,
        "salePrice": 2500,
        "description": "Custom football for the old world: Europe is calling, the blue background with the yellow stars of the founding members of the European Union. No minimum order required, scarf is knitted from one single piece with custom design.",
        "rating": 5,
        "tags": ["Women"],
        "size": ["M", "XL"],
        "category": "Scarves",
        "colors": ["Red"]
    },
    {
        "id": 5,
        "artNo": "1000-0052",
        "name": "Football Scarf Christmas",
        "slug": "6f",
        "pictures": ["scarves/football-scarf-christmas.jpg", "scarves/football-scarf-christmas.jpg"],
        "stock": 32,
        "price": 3500,
        "discount": 1000,
        "salePrice": 2500,
        "description": "Custom football christmas scarf santa would be proud of: the perfect gift for fans. Just add your FC, united or city logo, and off you go in christmas or team colors. Woolen soccer scarves to warm your neck in winter, as birthday gift or present for fellow supporters. Have yours personalized and knitted today.",
        "rating": 5,
        "tags": ["Women"],
        "size": ["M", "XL"],
        "category": "Scarves",
        "colors": ["Red"]
    },
    {
        "id": 6,
        "artNo": "1000-0053",
        "slug": "7g",
        "name": "Football Scarf Black White",
        "pictures": ["scarves/football-scarf-white-black.jpg", "scarves/football-scarf-white-black.jpg"],
        "stock": 32,
        "price": 3500,
        "discount": 1000,
        "salePrice": 2500,
        "description": "Football scarf with half/half design. The custom scarf for your team in black and white. Design online and create your custom team scarf today. Design with logo, text, cliparts etc. Design is knitted in.",
        "rating": 5,
        "tags": ["Women"],
        "size": ["M", "XL"],
        "category": "Scarves",
        "colors": ["Red"]
    },
    {
        "id": 7,
        "artNo": "1000-0054",
        "name": "Football Scarf Blue Yellow",
        "slug": "8h",
        "pictures": ["scarves/football-scarf-blue-yellow.jpg", "scarves/football-scarf-blue-yellow.jpg"],
        "stock": 32,
        "price": 3500,
        "discount": 1000,
        "salePrice": 2500,
        "description": "Football scarf with half/half design. The custom scarf for your team in blue and yellow. Design online and create your custom team scarf today. Design with logo, text, cliparts etc. Design is knitted in.",
        "rating": 5,
        "tags": ["Women"],
        "size": ["M", "XL"],
        "category": "Scarves",
        "colors": ["Red"]
    },
    {
        "id": 8,
        "artNo": "1000-0055",
        "name": "Football Scarf Red Black",
        "slug": "9i",
        "pictures": ["scarves/football-scarf-red-black.jpg", "scarves/football-scarf-red-black.jpg"],
        "stock": 32,
        "price": 3500,
        "discount": 1000,
        "salePrice": 2500,
        "description": "Football scarf with half/half design. The custom scarf for your team in red and black. Design online and create your custom team scarf today. Design with logo, text, cliparts etc. Design is knitted in.",
        "rating": 5,
        "tags": ["Women"],
        "size": ["M", "XL"],
        "category": "Scarves",
        "colors": ["Red"]
    },
    {
        "id": 9,
        "artNo": "1000-0056",
        "slug": "10j",
        "name": "Football Scarf White Blue",
        "pictures": ["scarves/football-scarf-white-blue.jpg", "scarves/football-scarf-white-blue.jpg"],
        "stock": 32,
        "price": 3500,
        "discount": 1000,
        "salePrice": 2500,
        "description": "Football scarf with half/half design. The custom scarf for your team in blue and white. Design online and create your custom team scarf today. Design with logo, text, cliparts etc. Design is knitted in.",
        "rating": 5,
        "tags": ["Women"],
        "size": ["M", "XL"],
        "category": "Scarves",
        "colors": ["Red"]
    },
    {
        "id": 10,
        "artNo": "1000-0057",
        "name": "Football Scarf Dark Blue White",
        "slug": "11k",
        "pictures": ["scarves/footall-scarf-white-dark-blue.jpg", "scarves/footall-scarf-white-dark-blue.jpg"],
        "stock": 32,
        "price": 3500,
        "discount": 1000,
        "salePrice": 2500,
        "description": "Football scarf with half/half design. The custom scarf for your team in dark blue and white. Design online and create your custom team scarf today. Design with logo, text, cliparts etc. Design is knitted in.",
        "rating": 5,
        "tags": ["Women"],
        "size": ["M", "XL"],
        "category": "Scarves",
        "colors": ["Red"]
    },
    {
        "id": 11,
        "artNo": "1000-0058",
        "name": "Football Scarf Yellow Red",
        "slug": "12l",
        "pictures": ["scarves/football-scarf-yellow-red.jpg", "scarves/football-scarf-yellow-red.jpg"],
        "stock": 32,
        "price": 3500,
        "discount": 1000,
        "salePrice": 2500,
        "description": "Football scarf with half/half design. The custom scarf for your team in yellow and red. Design online and create your custom team scarf today. Design with logo, text, cliparts etc. Design is knitted in.",
        "rating": 5,
        "tags": ["Women"],
        "size": ["M", "XL"],
        "category": "Scarves",
        "colors": ["Red"]
    },
   
]