/**
 *  Product List
 */

export default [
    {
        "id": 0,
        "name": "Fan Scarf Marathon",
        "slug": "1a",
        "pictures": ["scarves/fan-scarf-marathon.jpg", "scarves/fan-scarf-marathon.jpg"],
        "stock": 32,
        "price": 3500,
        // "discount": 1000,
        "salePrice": 2500,
        "description": "Adjustable and removable wide shoulder strap. Lined interior. Magnetic clasp closure.",
        "rating": 5,
        "tags": ["Women"],
        "size": ["M", "XL"],
        "category": "Scarves",
        "colors": ["Red"]
    },
    {
        "id": 1,
        "name": "Football Scarf Blue White",
        "slug": "2b",
        "pictures": ["scarves/football-scarf-blue-white.jpg", "scarves/football-scarf-blue-white.jpg"],
        "stock": 32,
        "price": 3500,
        "discount": 1000,
        "salePrice": 2500,
        "description": "Adjustable and removable wide shoulder strap. Lined interior. Magnetic clasp closure.",
        "rating": 5,
        "tags": ["Scarves"],
        "size": ["M", "XL"],
        "category": "Scarves",
        "colors": ["Red"]
    },
    {
        "id": 2,
        "name": "Football Scarf Darts",
        "slug": "3c",
        "pictures": ["scarves/football-scarf-darts.jpg", "scarves/football-scarf-darts.jpg"],
        "stock": 32,
        "price": 3500,
        "discount": 1000,
        "salePrice": 2500,
        "description": "Adjustable and removable wide shoulder strap. Lined interior. Magnetic clasp closure.",
        "rating": 5,
        "tags": ["Scarves"],
        "size": ["M", "XL"],
        "category": "Scarves",
        "colors": ["Red"]
    },
    {
        "id": 3,
        "name": "Football Scarf Leather",
        "slug": "4d",
        "pictures": ["scarves/football-scarf-leather.jpg", "scarves/football-scarf-leather.jpg"],
        "stock": 32,
        "price": 3500,
        "discount": 1000,
        "salePrice": 2500,
        "description": "Adjustable and removable wide shoulder strap. Lined interior. Magnetic clasp closure.",
        "rating": 5,
        "tags": ["Scarves"],
        "size": ["M", "XL"],
        "category": "Scarves",
        "colors": ["Red"]
    },
    {
        "id": 4,
        "name": "Football Scarf Europe",
        "slug": "5e",
        "pictures": ["scarves/football-scarf-europe.jpg", "scarves/football-scarf-europe.jpg"],
        "stock": 32,
        "price": 3500,
        "discount": 1000,
        "salePrice": 2500,
        "description": "Adjustable and removable wide shoulder strap. Lined interior. Magnetic clasp closure.",
        "rating": 5,
        "tags": ["Women"],
        "size": ["M", "XL"],
        "category": "Scarves",
        "colors": ["Red"]
    },
    {
        "id": 5,
        "name": "Football Scarf Christmas",
        "slug": "6f",
        "pictures": ["scarves/football-scarf-christmas.jpg", "scarves/football-scarf-christmas.jpg"],
        "stock": 32,
        "price": 3500,
        "discount": 1000,
        "salePrice": 2500,
        "description": "Adjustable and removable wide shoulder strap. Lined interior. Magnetic clasp closure.",
        "rating": 5,
        "tags": ["Women"],
        "size": ["M", "XL"],
        "category": "Scarves",
        "colors": ["Red"]
    },
    {
        "id": 6,
        "slug": "7g",
        "name": "Football Bar Scarf",
        "pictures": ["scarves/football-scarf-white-black.jpg", "scarves/football-scarf-white-black.jpg"],
        "stock": 32,
        "price": 3500,
        "discount": 1000,
        "salePrice": 2500,
        "description": "Adjustable and removable wide shoulder strap. Lined interior. Magnetic clasp closure.",
        "rating": 5,
        "tags": ["Women"],
        "size": ["M", "XL"],
        "category": "Scarves",
        "colors": ["Red"]
    },
    {
        "id": 7,
        "name": "Football Bar Scarf",
        "slug": "8h",
        "pictures": ["scarves/football-scarf-blue-yellow.jpg", "scarves/football-scarf-blue-yellow.jpg"],
        "stock": 32,
        "price": 3500,
        "discount": 1000,
        "salePrice": 2500,
        "description": "Adjustable and removable wide shoulder strap. Lined interior. Magnetic clasp closure.",
        "rating": 5,
        "tags": ["Women"],
        "size": ["M", "XL"],
        "category": "Scarves",
        "colors": ["Red"]
    },
    {
        "id": 8,
        "name": "Knitted Sports Scraf",
        "slug": "9i",
        "pictures": ["scarves/fan-scarf-marathon.jpg", "scarves/fan-scarf-marathon.jpg"],
        "stock": 32,
        "price": 3500,
        "discount": 1000,
        "salePrice": 2500,
        "description": "Adjustable and removable wide shoulder strap. Lined interior. Magnetic clasp closure.",
        "rating": 5,
        "tags": ["Women"],
        "size": ["M", "XL"],
        "category": "Scarves",
        "colors": ["Red"]
    },
    {
        "id": 9,
        "slug": "10j",
        "name": "Knitted Sports Scraf",
        "pictures": ["scarves/fan-scarf-marathon.jpg", "scarves/fan-scarf-marathon.jpg"],
        "stock": 32,
        "price": 3500,
        "discount": 1000,
        "salePrice": 2500,
        "description": "Adjustable and removable wide shoulder strap. Lined interior. Magnetic clasp closure.",
        "rating": 5,
        "tags": ["Women"],
        "size": ["M", "XL"],
        "category": "Scarves",
        "colors": ["Red"]
    },
    {
        "id": 10,
        "name": "Knitted Sports Scraf",
        "slug": "11k",
        "pictures": ["scarves/fan-scarf-marathon.jpg", "scarves/fan-scarf-marathon.jpg"],
        "stock": 32,
        "price": 3500,
        "discount": 1000,
        "salePrice": 2500,
        "description": "Adjustable and removable wide shoulder strap. Lined interior. Magnetic clasp closure.",
        "rating": 5,
        "tags": ["Women"],
        "size": ["M", "XL"],
        "category": "Scarves",
        "colors": ["Red"]
    },
    {
        "id": 11,
        "name": "Knitted Sports Scraf",
        "slug": "12l",
        "pictures": ["scarves/fan-scarf-marathon.jpg", "scarves/fan-scarf-marathon.jpg"],
        "stock": 32,
        "price": 3500,
        "discount": 1000,
        "salePrice": 2500,
        "description": "Adjustable and removable wide shoulder strap. Lined interior. Magnetic clasp closure.",
        "rating": 5,
        "tags": ["Women"],
        "size": ["M", "XL"],
        "category": "Scarves",
        "colors": ["Red"]
    },
   
]