/**
 *  Product List
 */

export default [
    {
        "id": 0,
        "name": "Fan Scarf Marathon",
        "slug": "1a",
        "pictures": ["scarves/fan-scarf-marathon1.jpg", "scarves/fan-scarf-marathon1.jpg"],
        "stock": 32,
        "price": 3500,
        // "discount": 1000,
        "salePrice": 2500,
        "description": "Adjustable and removable wide shoulder strap. Lined interior. Magnetic clasp closure.",
        "rating": 5,
        "tags": ["Women"],
        "size": ["M", "XL"],
        "category": "Scarves",
        "colors": ["Red"]
    },
    {
        "id": 1,
        "name": "Fan Scarf Marathon",
        "slug": "2b",
        "pictures": ["scarves/fan-scarf-marathon.jpg", "scarves/fan-scarf-marathon.jpg"],
        "stock": 32,
        "price": 3500,
        "discount": 1000,
        "salePrice": 2500,
        "description": "Adjustable and removable wide shoulder strap. Lined interior. Magnetic clasp closure.",
        "rating": 5,
        "tags": ["Scarves"],
        "size": ["M", "XL"],
        "category": "Scarves",
        "colors": ["Red"]
    },
    {
        "id": 2,
        "name": "Fan Scarf Marathon",
        "slug": "3c",
        "pictures": ["scarves/fan-scarf-marathon1.jpg", "scarves/fan-scarf-marathon1.jpg"],
        "stock": 32,
        "price": 3500,
        "discount": 1000,
        "salePrice": 2500,
        "description": "Adjustable and removable wide shoulder strap. Lined interior. Magnetic clasp closure.",
        "rating": 5,
        "tags": ["Scarves"],
        "size": ["M", "XL"],
        "category": "Scarves",
        "colors": ["Red"]
    },
    {
        "id": 3,
        "name": "Fan Scarf Marathon",
        "slug": "4d",
        "pictures": ["scarves/fan-scarf-marathon1.jpg", "scarves/fan-scarf-marathon1.jpg"],
        "stock": 32,
        "price": 3500,
        "discount": 1000,
        "salePrice": 2500,
        "description": "Adjustable and removable wide shoulder strap. Lined interior. Magnetic clasp closure.",
        "rating": 5,
        "tags": ["Scarves"],
        "size": ["M", "XL"],
        "category": "Scarves",
        "colors": ["Red"]
    },
    {
        "id": 4,
        "name": "Fan Scarf Marathon",
        "slug": "5e",
        "pictures": ["scarves/fan-scarf-marathon1.jpg", "scarves/fan-scarf-marathon1.jpg"],
        "stock": 32,
        "price": 3500,
        "discount": 1000,
        "salePrice": 2500,
        "description": "Adjustable and removable wide shoulder strap. Lined interior. Magnetic clasp closure.",
        "rating": 5,
        "tags": ["Women"],
        "size": ["M", "XL"],
        "category": "Scarves",
        "colors": ["Red"]
    },
    {
        "id": 5,
        "name": "Knitted Sports Scraf",
        "slug": "6f",
        "pictures": ["scarves/fan-scarf-marathon.jpg", "scarves/fan-scarf-marathon.jpg"],
        "stock": 32,
        "price": 3500,
        "discount": 1000,
        "salePrice": 2500,
        "description": "Adjustable and removable wide shoulder strap. Lined interior. Magnetic clasp closure.",
        "rating": 5,
        "tags": ["Women"],
        "size": ["M", "XL"],
        "category": "Scarves",
        "colors": ["Red"]
    },
    {
        "id": 6,
        "slug": "7g",
        "name": "Knitted Sports Scraf",
        "pictures": ["scarves/fan-scarf-marathon.jpg", "scarves/fan-scarf-marathon.jpg"],
        "stock": 32,
        "price": 3500,
        "discount": 1000,
        "salePrice": 2500,
        "description": "Adjustable and removable wide shoulder strap. Lined interior. Magnetic clasp closure.",
        "rating": 5,
        "tags": ["Women"],
        "size": ["M", "XL"],
        "category": "Scarves",
        "colors": ["Red"]
    },
    {
        "id": 7,
        "name": "Knitted Sports Scraf",
        "slug": "8h",
        "pictures": ["scarves/fan-scarf-marathon.jpg", "scarves/fan-scarf-marathon.jpg"],
        "stock": 32,
        "price": 3500,
        "discount": 1000,
        "salePrice": 2500,
        "description": "Adjustable and removable wide shoulder strap. Lined interior. Magnetic clasp closure.",
        "rating": 5,
        "tags": ["Women"],
        "size": ["M", "XL"],
        "category": "Scarves",
        "colors": ["Red"]
    },
    {
        "id": 8,
        "name": "Knitted Sports Scraf",
        "slug": "9i",
        "pictures": ["scarves/fan-scarf-marathon.jpg", "scarves/fan-scarf-marathon.jpg"],
        "stock": 32,
        "price": 3500,
        "discount": 1000,
        "salePrice": 2500,
        "description": "Adjustable and removable wide shoulder strap. Lined interior. Magnetic clasp closure.",
        "rating": 5,
        "tags": ["Women"],
        "size": ["M", "XL"],
        "category": "Scarves",
        "colors": ["Red"]
    },
    {
        "id": 9,
        "slug": "10j",
        "name": "Knitted Sports Scraf",
        "pictures": ["scarves/fan-scarf-marathon.jpg", "scarves/fan-scarf-marathon.jpg"],
        "stock": 32,
        "price": 3500,
        "discount": 1000,
        "salePrice": 2500,
        "description": "Adjustable and removable wide shoulder strap. Lined interior. Magnetic clasp closure.",
        "rating": 5,
        "tags": ["Women"],
        "size": ["M", "XL"],
        "category": "Scarves",
        "colors": ["Red"]
    },
    {
        "id": 10,
        "name": "Knitted Sports Scraf",
        "slug": "11k",
        "pictures": ["scarves/fan-scarf-marathon.jpg", "scarves/fan-scarf-marathon.jpg"],
        "stock": 32,
        "price": 3500,
        "discount": 1000,
        "salePrice": 2500,
        "description": "Adjustable and removable wide shoulder strap. Lined interior. Magnetic clasp closure.",
        "rating": 5,
        "tags": ["Women"],
        "size": ["M", "XL"],
        "category": "Scarves",
        "colors": ["Red"]
    },
    {
        "id": 11,
        "name": "Knitted Sports Scraf",
        "slug": "12l",
        "pictures": ["scarves/fan-scarf-marathon.jpg", "scarves/fan-scarf-marathon.jpg"],
        "stock": 32,
        "price": 3500,
        "discount": 1000,
        "salePrice": 2500,
        "description": "Adjustable and removable wide shoulder strap. Lined interior. Magnetic clasp closure.",
        "rating": 5,
        "tags": ["Women"],
        "size": ["M", "XL"],
        "category": "Scarves",
        "colors": ["Red"]
    },
   
]